run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: advent-of-code-2024

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck